# CMake generated Testfile for 
# Source directory: C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests
# Build directory: C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hostkey "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_hostkey.exe")
  set_tests_properties(test_hostkey PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hostkey "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_hostkey.exe")
  set_tests_properties(test_hostkey PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hostkey "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_hostkey.exe")
  set_tests_properties(test_hostkey PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hostkey "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_hostkey.exe")
  set_tests_properties(test_hostkey PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_hostkey NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hostkey_hash "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_hostkey_hash.exe")
  set_tests_properties(test_hostkey_hash PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hostkey_hash "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_hostkey_hash.exe")
  set_tests_properties(test_hostkey_hash PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hostkey_hash "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_hostkey_hash.exe")
  set_tests_properties(test_hostkey_hash PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hostkey_hash "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_hostkey_hash.exe")
  set_tests_properties(test_hostkey_hash PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_hostkey_hash NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_password_auth_succeeds_with_correct_credentials "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_password_auth_succeeds_with_correct_credentials.exe")
  set_tests_properties(test_password_auth_succeeds_with_correct_credentials PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_password_auth_succeeds_with_correct_credentials "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_password_auth_succeeds_with_correct_credentials.exe")
  set_tests_properties(test_password_auth_succeeds_with_correct_credentials PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_password_auth_succeeds_with_correct_credentials "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_password_auth_succeeds_with_correct_credentials.exe")
  set_tests_properties(test_password_auth_succeeds_with_correct_credentials PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_password_auth_succeeds_with_correct_credentials "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_password_auth_succeeds_with_correct_credentials.exe")
  set_tests_properties(test_password_auth_succeeds_with_correct_credentials PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_password_auth_succeeds_with_correct_credentials NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_password_auth_fails_with_wrong_password "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_password_auth_fails_with_wrong_password.exe")
  set_tests_properties(test_password_auth_fails_with_wrong_password PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_password_auth_fails_with_wrong_password "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_password_auth_fails_with_wrong_password.exe")
  set_tests_properties(test_password_auth_fails_with_wrong_password PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_password_auth_fails_with_wrong_password "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_password_auth_fails_with_wrong_password.exe")
  set_tests_properties(test_password_auth_fails_with_wrong_password PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_password_auth_fails_with_wrong_password "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_password_auth_fails_with_wrong_password.exe")
  set_tests_properties(test_password_auth_fails_with_wrong_password PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_password_auth_fails_with_wrong_password NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_password_auth_fails_with_wrong_username "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_password_auth_fails_with_wrong_username.exe")
  set_tests_properties(test_password_auth_fails_with_wrong_username PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_password_auth_fails_with_wrong_username "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_password_auth_fails_with_wrong_username.exe")
  set_tests_properties(test_password_auth_fails_with_wrong_username PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_password_auth_fails_with_wrong_username "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_password_auth_fails_with_wrong_username.exe")
  set_tests_properties(test_password_auth_fails_with_wrong_username PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_password_auth_fails_with_wrong_username "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_password_auth_fails_with_wrong_username.exe")
  set_tests_properties(test_password_auth_fails_with_wrong_username PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_password_auth_fails_with_wrong_username NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_public_key_auth_fails_with_wrong_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_public_key_auth_fails_with_wrong_key.exe")
  set_tests_properties(test_public_key_auth_fails_with_wrong_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_public_key_auth_fails_with_wrong_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_public_key_auth_fails_with_wrong_key.exe")
  set_tests_properties(test_public_key_auth_fails_with_wrong_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_public_key_auth_fails_with_wrong_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_public_key_auth_fails_with_wrong_key.exe")
  set_tests_properties(test_public_key_auth_fails_with_wrong_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_public_key_auth_fails_with_wrong_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_public_key_auth_fails_with_wrong_key.exe")
  set_tests_properties(test_public_key_auth_fails_with_wrong_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_public_key_auth_fails_with_wrong_key NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_public_key_auth_succeeds_with_correct_rsa_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_public_key_auth_succeeds_with_correct_rsa_key.exe")
  set_tests_properties(test_public_key_auth_succeeds_with_correct_rsa_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_public_key_auth_succeeds_with_correct_rsa_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_public_key_auth_succeeds_with_correct_rsa_key.exe")
  set_tests_properties(test_public_key_auth_succeeds_with_correct_rsa_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_public_key_auth_succeeds_with_correct_rsa_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_public_key_auth_succeeds_with_correct_rsa_key.exe")
  set_tests_properties(test_public_key_auth_succeeds_with_correct_rsa_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_public_key_auth_succeeds_with_correct_rsa_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_public_key_auth_succeeds_with_correct_rsa_key.exe")
  set_tests_properties(test_public_key_auth_succeeds_with_correct_rsa_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_public_key_auth_succeeds_with_correct_rsa_key NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_public_key_auth_succeeds_with_correct_dsa_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_public_key_auth_succeeds_with_correct_dsa_key.exe")
  set_tests_properties(test_public_key_auth_succeeds_with_correct_dsa_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_public_key_auth_succeeds_with_correct_dsa_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_public_key_auth_succeeds_with_correct_dsa_key.exe")
  set_tests_properties(test_public_key_auth_succeeds_with_correct_dsa_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_public_key_auth_succeeds_with_correct_dsa_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_public_key_auth_succeeds_with_correct_dsa_key.exe")
  set_tests_properties(test_public_key_auth_succeeds_with_correct_dsa_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_public_key_auth_succeeds_with_correct_dsa_key "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_public_key_auth_succeeds_with_correct_dsa_key.exe")
  set_tests_properties(test_public_key_auth_succeeds_with_correct_dsa_key PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_public_key_auth_succeeds_with_correct_dsa_key NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_keyboard_interactive_auth_fails_with_wrong_response "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_keyboard_interactive_auth_fails_with_wrong_response.exe")
  set_tests_properties(test_keyboard_interactive_auth_fails_with_wrong_response PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_keyboard_interactive_auth_fails_with_wrong_response "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_keyboard_interactive_auth_fails_with_wrong_response.exe")
  set_tests_properties(test_keyboard_interactive_auth_fails_with_wrong_response PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_keyboard_interactive_auth_fails_with_wrong_response "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_keyboard_interactive_auth_fails_with_wrong_response.exe")
  set_tests_properties(test_keyboard_interactive_auth_fails_with_wrong_response PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_keyboard_interactive_auth_fails_with_wrong_response "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_keyboard_interactive_auth_fails_with_wrong_response.exe")
  set_tests_properties(test_keyboard_interactive_auth_fails_with_wrong_response PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_keyboard_interactive_auth_fails_with_wrong_response NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_keyboard_interactive_auth_succeeds_with_correct_response "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Debug/test_keyboard_interactive_auth_succeeds_with_correct_response.exe")
  set_tests_properties(test_keyboard_interactive_auth_succeeds_with_correct_response PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_keyboard_interactive_auth_succeeds_with_correct_response "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/Release/test_keyboard_interactive_auth_succeeds_with_correct_response.exe")
  set_tests_properties(test_keyboard_interactive_auth_succeeds_with_correct_response PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_keyboard_interactive_auth_succeeds_with_correct_response "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/MinSizeRel/test_keyboard_interactive_auth_succeeds_with_correct_response.exe")
  set_tests_properties(test_keyboard_interactive_auth_succeeds_with_correct_response PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_keyboard_interactive_auth_succeeds_with_correct_response "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests/RelWithDebInfo/test_keyboard_interactive_auth_succeeds_with_correct_response.exe")
  set_tests_properties(test_keyboard_interactive_auth_succeeds_with_correct_response PROPERTIES  WORKING_DIRECTORY "C:/Projects/MyProjects/libssh2-1.8.0-VC2008-MT-32-SRC-CMAKE/tests")
else()
  add_test(test_keyboard_interactive_auth_succeeds_with_correct_response NOT_AVAILABLE)
endif()
